name: 'Auto-rebase feature branch from master'
on:
  push:
    branches:
      - master

jobs:
  Rebase:
    name: 'Auto-rebase feature branch on push into master'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: test
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user email and name
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
        continue-on-error: false

      - name: Pull latest changes from master
        run: |
          git fetch -ap
          git log --graph --pretty=format:%s
        continue-on-error: false

      - name: Checkout to develop
        run: |
          git checkout test
        continue-on-error: false

      - name: Make sure develop has latest changes
        run: |
          git reset origin test
        continue-on-error: false

      - name: Perform rebase
        run: |
          git rebase origin master
        continue-on-error: false

      - name: Force push changes to test
        run: |
          git push origin test --force-with-lease
          git log --graph --pretty=format:%s
        continue-on-error: false