name: 'Auto-rebase develop branch from master'
on:
  push:
    branches:
      - master

jobs:
  Rebase:
    name: 'Auto-rebase develop branch on push into master'
    runs-on: ubuntu-latest
    steps:

      - name: Check out in Api Platform repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: test
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user email and name
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
        continue-on-error: false

      - name: Checkout to master
        run: |
          git checkout master
        continue-on-error: false

      - name: Pull latest changes from master
        run: |
          git pull origin master
          git log --graph --pretty=format:%s
        continue-on-error: false

      - name: Checkout to develop
        run: |
          git checkout test
        continue-on-error: false

      - name: Make sure develop has latest changes
        run: |
          git pull origin test
        continue-on-error: false

      - name: Perform rebase
        run: |
          git rebase master
        continue-on-error: false

      - name: Force push changes to test
        run: |
          git push origin test --force-with-lease
          git log --graph --pretty=format:%s
        continue-on-error: false