name: autoupdate
on:
  push:
     branches:
       - master
jobs:
  rebase_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test

      - name: Checkout dev branch and rebase onto main
        run: |
          git config set advice.mergeConflict false
          git config set advice.detachedHead false
          git fetch -ap
          git checkout -f origin/test
          git rebase origin/master

      - name: Push rebased dev branch
        run: |
          git push -f origin/test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
