name: autoupdate
on:
  push:
     branches:
       - master
jobs:
  rebase_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Checkout dev branch and rebase onto main
        run: |
          git fetch origin test
          git checkout test
          git rebase origin master

      - name: Push rebased dev branch
        run: |
          git push -f origin test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
